export const PRODUCT_LOADING="PRODUCT_LOADING";
export const CART_LOADING="CART_LOADING";
export const GET_ALL_PRODUCTS="GET_ALL_PRODUCTS";
export const HOME_DATA="HOME_DATA";
export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_TO_CART="REMOVE_TO_CART";
export const INCREASE_CART_ITEM="INCREASE_CART_ITEM";
export const DECREASE_CART_ITEM="DECREASE_CART_ITEM";
export const REMOVE_ALL_IN_CART="REMOVE_ALL_IN_CART";






